const NSE_TICKERS = [
    // === NIFTY 50 & MEGA CAPS ===
    ["RELIANCE", "Reliance Industries Ltd"],
    ["TCS", "Tata Consultancy Services Ltd"],
    ["HDFCBANK", "HDFC Bank Ltd"],
    ["ICICIBANK", "ICICI Bank Ltd"],
    ["INFY", "Infosys Ltd"],
    ["SBIN", "State Bank Of India"],
    ["BHARTIARTL", "Bharti Airtel Ltd"],
    ["BAJFINANCE", "Bajaj Finance Ltd"],
    ["LICI", "Life Insurance Corporation Of India"],
    ["LT", "Larsen & Toubro Ltd"],
    ["HINDUNILVR", "Hindustan Unilever Ltd"],
    ["SUNPHARMA", "Sun Pharmaceutical Industries Ltd"],
    ["MARUTI", "Maruti Suzuki India Ltd"],
    ["AXISBANK", "Axis Bank Ltd"],
    ["TITAN", "Titan Company Ltd"],
    ["KOTAKBANK", "Kotak Mahindra Bank Ltd"],
    ["ITC", "ITC Ltd"],
    ["ONGC", "Oil & Natural Gas Corporation Ltd"],
    ["NTPC", "NTPC Ltd"],
    ["POWERGRID", "Power Grid Corporation Of India Ltd"],
    ["M&M", "Mahindra & Mahindra Ltd"],
    ["TATAMOTORS", "Tata Motors Ltd"],
    ["TATASTEEL", "Tata Steel Ltd"],
    ["JSWSTEEL", "JSW Steel Ltd"],
    ["WIPRO", "Wipro Ltd"],
    ["HCLTECH", "HCL Technologies Ltd"],
    ["ASIANPAINT", "Asian Paints Ltd"],
    ["ULTRACEMCO", "UltraTech Cement Ltd"],
    ["NESTLEIND", "Nestle India Ltd"],
    ["BAJAJFINSV", "Bajaj Finserv Ltd"],
    ["BAJAJ-AUTO", "Bajaj Auto Ltd"],
    ["HINDALCO", "Hindalco Industries Ltd"],
    ["COALINDIA", "Coal India Ltd"],
    ["DRREDDY", "Dr Reddys Laboratories Ltd"],
    ["CIPLA", "Cipla Ltd"],
    ["DIVISLAB", "Divis Laboratories Ltd"],
    ["APOLLOHOSP", "Apollo Hospitals Enterprise Ltd"],
    ["EICHERMOT", "Eicher Motors Ltd"],
    ["GRASIM", "Grasim Industries Ltd"],
    ["HEROMOTOCO", "Hero MotoCorp Ltd"],
    ["INDUSINDBK", "IndusInd Bank Ltd"],
    ["SBILIFE", "SBI Life Insurance Company Ltd"],
    ["HDFCLIFE", "HDFC Life Insurance Company Ltd"],
    ["BRITANNIA", "Britannia Industries Ltd"],
    ["TECHM", "Tech Mahindra Ltd"],
    ["BPCL", "Bharat Petroleum Corporation Ltd"],
    ["SHRIRAMFIN", "Shriram Finance Ltd"],
    ["TATACONSUM", "Tata Consumer Products Ltd"],
    ["UPL", "UPL Ltd"],
    ["LTIM", "LTIMindtree Ltd"],

    // === ADANI GROUP ===
    ["ADANIENT", "Adani Enterprises Ltd"],
    ["ADANIPORTS", "Adani Ports & Special Economic Zone Ltd"],
    ["ADANIPOWER", "Adani Power Ltd"],
    ["ADANIGREEN", "Adani Green Energy Ltd"],
    ["ADANIENSOL", "Adani Energy Solutions Ltd"],
    ["ATGL", "Adani Total Gas Ltd"],
    ["AWL", "Adani Wilmar Ltd"],
    ["ACC", "ACC Ltd"],
    ["AMBUJACEM", "Ambuja Cements Ltd"],
    ["NDTV", "New Delhi Television Ltd"],

    // === RAILWAYS & DEFENSE (HIGH MOMENTUM) ===
    ["IRFC", "Indian Railway Finance Corp"],
    ["RVNL", "Rail Vikas Nigam Ltd"],
    ["IRCON", "Ircon International Ltd"],
    ["IRCTC", "Indian Railway Catering & Tourism Corp Ltd"],
    ["CONCOR", "Container Corporation Of India Ltd"],
    ["BHEL", "Bharat Heavy Electricals Ltd"],
    ["HAL", "Hindustan Aeronautics Ltd"],
    ["BEL", "Bharat Electronics Ltd"],
    ["BDL", "Bharat Dynamics Ltd"],
    ["MAZDOCK", "Mazagon Dock Shipbuilders Ltd"],
    ["COCHINSHIP", "Cochin Shipyard Ltd"],
    ["DATAPATTERNS", "Data Patterns (India) Ltd"],
    ["BEML", "BEML Ltd"],
    ["GSL", "Goa Shipyard Ltd"],
    ["TITAGARH", "Titagarh Rail Systems Ltd"],
    ["TEXRAIL", "Texmaco Rail & Engineering Ltd"],
    ["RAILTEL", "RailTel Corporation Of India Ltd"],

    // === BANKING & FINANCIAL SERVICES ===
    ["PNB", "Punjab National Bank"],
    ["BANKBARODA", "Bank Of Baroda"],
    ["CANBK", "Canara Bank"],
    ["UNIONBANK", "Union Bank Of India"],
    ["IOB", "Indian Overseas Bank"],
    ["IDFCFIRSTB", "IDFC First Bank Ltd"],
    ["FEDERALBNK", "Federal Bank Ltd"],
    ["AUBANK", "AU Small Finance Bank Ltd"],
    ["BANDHANBNK", "Bandhan Bank Ltd"],
    ["IDBI", "IDBI Bank Ltd"],
    ["MUTHOOTFIN", "Muthoot Finance Ltd"],
    ["CHOLAFIN", "Cholamandalam Investment & Finance"],
    ["MANAPPURAM", "Manappuram Finance Ltd"],
    ["PFC", "Power Finance Corporation Ltd"],
    ["RECLTD", "REC Ltd"],
    ["IREDA", "Indian Renewable Energy Dev Agency"],
    ["CENTRALBK", "Central Bank Of India"],
    ["MAHABANK", "Bank Of Maharashtra"],
    ["UCOBANK", "UCO Bank"],
    ["BANKINDIA", "Bank Of India"],
    ["PSB", "Punjab & Sind Bank"],
    ["SOUTHBANK", "South Indian Bank Ltd"],
    ["KARURVYSYA", "Karur Vysya Bank Ltd"],
    ["CUB", "City Union Bank Ltd"],
    ["J&KBANK", "Jammu & Kashmir Bank Ltd"],
    ["KFINTECH", "KFin Technologies Ltd"],
    ["CAMS", "Computer Age Management Services Ltd"],
    ["CDSL", "Central Depository Services India Ltd"],
    ["BSE", "BSE Ltd"],
    ["MCX", "Multi Commodity Exchange Of India Ltd"],
    ["ANGELONE", "Angel One Ltd"],
    ["MOTILALOFS", "Motilal Oswal Financial Services Ltd"],
    ["M&MFIN", "Mahindra & Mahindra Financial Services"],
    ["L&TFH", "L&T Finance Holdings Ltd"],
    ["BAJAJHLDNG", "Bajaj Holdings & Investment Ltd"],
    ["HUDCO", "Housing & Urban Development Corp Ltd"],
    ["JIOFIN", "Jio Financial Services Ltd"],

    // === NEW AGE TECH & INTERNET ===
    ["ZOMATO", "Zomato Ltd"],
    ["NYKAA", "FSN E-Commerce Ventures Ltd (Nykaa)"],
    ["PAYTM", "One 97 Communications Ltd (Paytm)"],
    ["POLICYBZR", "PB Fintech Ltd (Policybazaar)"],
    ["DELHIVERY", "Delhivery Ltd"],
    ["MAPMYINDIA", "C.E. Info Systems Ltd"],
    ["AFFLE", "Affle (India) Ltd"],
    ["NAUKRI", "Info Edge (India) Ltd"],
    ["HONASA", "Honasa Consumer Ltd (Mamaearth)"],
    ["IDEA", "Vodafone Idea Ltd"],

    // === ENERGY & POWER SEGMENT ===
    ["TATAPOWER", "Tata Power Company Ltd"],
    ["SUZLON", "Suzlon Energy Ltd"],
    ["NHPC", "NHPC Ltd"],
    ["SJVN", "SJVN Ltd"],
    ["GENSOL", "Gensol Engineering Ltd"],
    ["KPIGREEN", "KPI Green Energy Ltd"],
    ["INDOCO", "Indoco Remedies Ltd"],
    ["GAIL", "GAIL India Ltd"],
    ["OIL", "Oil India Ltd"],
    ["PETRONET", "Petronet LNG Ltd"],
    ["GSPL", "Gujarat State Petronet Ltd"],
    ["IGL", "Indraprastha Gas Ltd"],
    ["MGL", "Mahanagar Gas Ltd"],
    ["CESC", "CESC Ltd"],
    ["JSWENERGY", "JSW Energy Ltd"],
    ["TORNTPOWER", "Torrent Power Ltd"],

    // === AUTOMOBILES & AUTO ANCILLARIES ===
    ["ASHOKLEY", "Ashok Leyland Ltd"],
    ["BALKRISIND", "Balkrishna Industries Ltd"],
    ["MRF", "MRF Ltd"],
    ["APOLLOTYRE", "Apollo Tyres Ltd"],
    ["TVSMOTOR", "TVS Motor Company Ltd"],
    ["EXIDEIND", "Exide Industries Ltd"],
    ["AMARAJABAT", "Amara Raja Energy & Mobility Ltd"],
    ["SONACOMS", "Sona BLW Precision Forgings Ltd"],
    ["BOSCHLTD", "Bosch Ltd"],
    ["MOTHERSON", "Samvardhana Motherson International"],
    ["BHARATFORG", "Bharat Forge Ltd"],
    ["ENDURANCE", "Endurance Technologies Ltd"],
    ["CEAT", "CEAT Ltd"],
    ["JKTYRE", "JK Tyre & Industries Ltd"],
    ["BALAMINES", "Balaji Amines Ltd"],

    // === INFORMATION TECHNOLOGY (IT) ===
    ["PERSISTENT", "Persistent Systems Ltd"],
    ["COFORGE", "Coforge Ltd"],
    ["MPHASIS", "Mphasis Ltd"],
    ["LTTS", "L&T Technology Services Ltd"],
    ["KPITTECH", "KPIT Technologies Ltd"],
    ["TATAELXSI", "Tata Elxsi Ltd"],
    ["CYIENT", "Cyient Ltd"],
    ["SONATAANNW", "Sonata Software Ltd"],
    ["ZENSARTECH", "Zensar Technologies Ltd"],
    ["INTELLECT", "Intellect Design Arena Ltd"],
    ["TEJASNET", "Tejas Networks Ltd"],
    ["MASTEK", "Mastek Ltd"],
    [" BirlaSoft", "Birlasoft Ltd"],
    ["BSOFT", "Birlasoft Ltd"],

    // === PHARMACEUTICALS & HEALTHCARE ===
    ["ZYDUSLIFE", "Zydus Lifesciences Ltd"],
    ["LUPIN", "Lupin Ltd"],
    ["AUROPHARMA", "Aurobindo Pharma Ltd"],
    ["ALKEM", "Alkem Laboratories Ltd"],
    ["TORNTPHARM", "Torrent Pharmaceuticals Ltd"],
    ["BIOCON", "Biocon Ltd"],
    ["GLENMARK", "Glenmark Pharmaceuticals Ltd"],
    ["IPCALAB", "Ipca Laboratories Ltd"],
    ["GRANULES", "Granules India Ltd"],
    ["LAURUSLABS", "Laurus Labs Ltd"],
    ["NATCOPHARM", "Natco Pharma Ltd"],
    ["METROPOLIS", "Metropolis Healthcare Ltd"],
    ["LALPATHLAB", "Dr Lal PathLabs Ltd"],
    ["MAXHEALTH", "Max Healthcare Institute Ltd"],
    ["FORTIS", "Fortis Healthcare Ltd"],
    ["GLOBALHEALTH", "Global Health Ltd (Medanta)"],

    // === METALS & MINING ===
    ["SAIL", "Steel Authority Of India Ltd"],
    ["NMDC", "NMDC Ltd"],
    ["NATIONALUM", "National Aluminium Company Ltd"],
    ["JINDALSTEL", "Jindal Steel & Power Ltd"],
    ["VEDL", "Vedanta Ltd"],
    ["HINDZINC", "Hindustan Zinc Ltd"],
    ["TATASTEEL", "Tata Steel Ltd"],
    ["HINDALCO", "Hindalco Industries Ltd"],
    ["JSL", "Jindal Stainless Ltd"],
    ["WELCORP", "Welspun Corp Ltd"],

    // === INFRASTRUCTURE, CEMENT & REALTY ===
    ["DLF", "DLF Ltd"],
    ["GODREJPROP", "Godrej Properties Ltd"],
    ["OBEROIRLTY", "Oberoi Realty Ltd"],
    ["LODHA", "Macrotech Developers Ltd"],
    ["PHOENIXLTD", "Phoenix Mills Ltd"],
    ["SOBHA", "Sobha Ltd"],
    ["PRESTIGE", "Prestige Estates Projects Ltd"],
    ["BRIGADE", "Brigade Enterprises Ltd"],
    ["IRB", "IRB Infrastructure Developers Ltd"],
    ["GMRINFRA", "GMR Airports Infrastructure Ltd"],
    ["GMRAIRPORT", "GMR Airports Infrastructure Ltd"],
    ["NCC", "NCC Ltd"],
    ["HNGSNACK", "HG Infra Engineering Ltd"],
    ["INFRAREIT", "POWERGRID Infrastructure Investment"],
    ["JKCEMENT", "JK Cement Ltd"],
    ["RAMCOCEM", "The Ramco Cements Ltd"],
    ["SHRIRAMWAR", "Shriram Properties Ltd"],
    ["HEIDELBERG", "HeidelbergCement India Ltd"],
    ["INDIA CEMENTS", "The India Cements Ltd"],

    // === CONSUMER GOODS, FMCG & RETAIL ===
    ["PIDILITIND", "Pidilite Industries Ltd"],
    ["DABUR", "Dabur India Ltd"],
    ["GODREJCP", "Godrej Consumer Products Ltd"],
    ["MARICO", "Marico Ltd"],
    ["COLPAL", "Colgate Palmolive India Ltd"],
    ["DMART", "Avenue Supermarts Ltd"],
    ["TRENT", "Trent Ltd"],
    ["PAGEIND", "Page Industries Ltd"],
    ["KAYNES", "Kaynes Technology India Ltd"],
    ["DIXON", "Dixon Technologies India Ltd"],
    ["AMBER", "Amber Enterprises India Ltd"],
    ["VOLTAS", "Voltas Ltd"],
    ["BLUESTARCO", "Blue Star Ltd"],
    ["HAVELLS", "Havells India Ltd"],
    ["POLYCAB", "Polycab India Ltd"],
    ["ASTRAL", "Astral Ltd"],
    ["SUPREMEIND", "Supreme Industries Ltd"],
    ["CROMPTON", "Crompton Greaves Consumer Elec"],
    ["VGUARD", "V-Guard Industries Ltd"],
    ["RELAXO", "Relaxo Footwears Ltd"],
    ["BATAINDIA", "Bata India Ltd"],
    ["CAMPUS", "Campus Activewear Ltd"],
    ["VART", "V-Mart Retail Ltd"],
    ["ABFRL", "Aditya Birla Fashion & Retail Ltd"],
    ["DEVYANI", "Devyani International Ltd"],
    ["JUBLFOOD", "Jubilant Foodworks Ltd"],
    ["WESTLIFE", "Westlife Foodworld Ltd"],
    ["SAPPHIRE", "Sapphire Foods India Ltd"],

    // === CHEMICALS & FERTILIZERS ===
    ["TATACHEM", "Tata Chemicals Ltd"],
    ["DEEPAKNTR", "Deepak Nitrite Ltd"],
    ["SRF", "SRF Ltd"],
    ["PIIND", "PI Industries Ltd"],
    ["NAVINFLUOR", "Navin Fluorine International Ltd"],
    ["ATUL", "Atul Ltd"],
    ["FLUOROCHEM", "先进氟化工 (Gujarat Fluorochemicals)"],
    ["UPL", "UPL Ltd"],
    ["RCF", "Rashtriya Chemicals & Fertilizers Ltd"],
    ["FACT", "Fertilizers & Chemicals Travancore"],
    ["GNFC", "Gujarat Narmada Valley Fert & Chem"],
    ["GSFC", "Gujarat State Fertilizers & Chem"],
    ["COROMANDEL", "Coromandel International Ltd"],
    ["CHAMBLFERT", "Chambal Fertilizers & Chem Ltd"],

    // === MISCELLANEOUS / MID-CAP SPECIALS ===
    ["ZEEL", "Zee Entertainment Enterprises Ltd"],
    ["SUNTV", "Sun TV Network Ltd"],
    ["PVRINOX", "PVR Inox Ltd"],
    ["INDIGO", "InterGlobe Aviation Ltd (IndiGo)"],
    ["SPICEJET", "SpiceJet Ltd"],
    ["TATACOMM", "Tata Communications Ltd"],
    ["CUMMINSIND", "Cummins India Ltd"],
    ["SIEMENS", "Siemens Ltd"],
    ["ABB", "ABB India Ltd"],
    ["THERMAX", "Thermax Ltd"],
    ["IEX", "Indian Energy Exchange Ltd"],
    ["BLS", "BLS International Services Ltd"],
    ["ESCORTS", "Escorts Kubota Ltd"],
    ["GMDCLTD", "Gujarat Mineral Development Corp"],
    ["HUDCO", "Housing & Urban Development Corp"],
    ["GOCLCORP", "GOCL Corporation Ltd"],
    ["SWANENERGY", "Swan Energy Ltd"],
    ["HFCL", "HFCL Ltd"],
    ["ITI", "ITI Ltd"],
    ["TRIDENT", "Trident Ltd"],
    ["ALOKINDS", "Alok Industries Ltd"],
    ["BCG", "Brightcom Group Ltd"],
    ["SURYAROSNI", "Surya Roshni Ltd"],
    ["EASEMYTRIP", "Easy Trip Planners Ltd"],
    ["IRB", "IRB Infrastructure Developers Ltd"]
];