const NSE_TICKERS=[
["RELIANCE","Reliance Industries Ltd"],["TCS","Tata Consultancy Services Ltd"],["HDFCBANK","HDFC Bank Ltd"],
["ICICIBANK","ICICI Bank Ltd"],["INFY","Infosys Ltd"],["SBIN","State Bank Of India"],["BHARTIARTL","Bharti Airtel Ltd"],
["BAJFINANCE","Bajaj Finance Ltd"],["LICI","Life Insurance Corporation Of India"],["LT","Larsen & Toubro Ltd"],
["HINDUNILVR","Hindustan Unilever Ltd"],["SUNPHARMA","Sun Pharmaceutical Industries Ltd"],["MARUTI","Maruti Suzuki India Ltd"],
["ADANIPORTS","Adani Ports & Special Economic Zone Ltd"],["ADANIPOWER","Adani Power Ltd"],["AXISBANK","Axis Bank Ltd"],
["ADANIENT","Adani Enterprises Ltd"],["TITAN","Titan Company Ltd"],["KOTAKBANK","Kotak Mahindra Bank Ltd"],
["ITC","ITC Ltd"],["ONGC","Oil & Natural Gas Corporation Ltd"],["NTPC","NTPC Ltd"],["POWERGRID","Power Grid Corporation Of India Ltd"],
["M&M","Mahindra & Mahindra Ltd"],["TATAMOTORS","Tata Motors Ltd"],["TATASTEEL","Tata Steel Ltd"],["JSWSTEEL","JSW Steel Ltd"],
["WIPRO","Wipro Ltd"],["HCLTECH","HCL Technologies Ltd"],["ASIANPAINT","Asian Paints Ltd"],["ULTRACEMCO","UltraTech Cement Ltd"],
["NESTLEIND","Nestle India Ltd"],["BAJAJFINSV","Bajaj Finserv Ltd"],["BAJAJ-AUTO","Bajaj Auto Ltd"],["HINDALCO","Hindalco Industries Ltd"],
["COALINDIA","Coal India Ltd"],["DRREDDY","Dr Reddys Laboratories Ltd"],["CIPLA","Cipla Ltd"],["DIVISLAB","Divis Laboratories Ltd"],
["APOLLOHOSP","Apollo Hospitals Enterprise Ltd"],["EICHERMOT","Eicher Motors Ltd"],["GRASIM","Grasim Industries Ltd"],
["HEROMOTOCO","Hero MotoCorp Ltd"],["INDUSINDBK","IndusInd Bank Ltd"],["SBILIFE","SBI Life Insurance Company Ltd"],
["HDFCLIFE","HDFC Life Insurance Company Ltd"],["BRITANNIA","Britannia Industries Ltd"],["TECHM","Tech Mahindra Ltd"],
["BPCL","Bharat Petroleum Corporation Ltd"],["SHRIRAMFIN","Shriram Finance Ltd"],["TATACONSUM","Tata Consumer Products Ltd"],
["UPL","UPL Ltd"],["LTIM","LTIMindtree Ltd"],["VEDL","Vedanta Ltd"],["GAIL","GAIL India Ltd"],["PIDILITIND","Pidilite Industries Ltd"],
["DABUR","Dabur India Ltd"],["GODREJCP","Godrej Consumer Products Ltd"],["MARICO","Marico Ltd"],["COLPAL","Colgate Palmolive India Ltd"],
["SIEMENS","Siemens Ltd"],["ABB","ABB India Ltd"],["HAL","Hindustan Aeronautics Ltd"],["BEL","Bharat Electronics Ltd"],
["DLF","DLF Ltd"],["GODREJPROP","Godrej Properties Ltd"],["OBEROIRLTY","Oberoi Realty Ltd"],["IRCTC","Indian Railway Catering & Tourism Corp Ltd"],
["ZOMATO","Eternal Ltd (Zomato)"],["NYKAA","FSN E-Commerce Ventures Ltd (Nykaa)"],["PAYTM","One 97 Communications Ltd (Paytm)"],
["POLICYBZR","PB Fintech Ltd (Policybazaar)"],["DMART","Avenue Supermarts Ltd (DMart)"],["TRENT","Trent Ltd"],
["PAGEIND","Page Industries Ltd"],["MUTHOOTFIN","Muthoot Finance Ltd"],["CHOLAFIN","Cholamandalam Investment & Finance"],
["PNB","Punjab National Bank"],["BANKBARODA","Bank Of Baroda"],["CANBK","Canara Bank"],["IDFCFIRSTB","IDFC First Bank Ltd"],
["FEDERALBNK","Federal Bank Ltd"],["AUBANK","AU Small Finance Bank Ltd"],["BANDHANBNK","Bandhan Bank Ltd"],
["ZEEL","Zee Entertainment Enterprises Ltd"],["SUNTV","Sun TV Network Ltd"],["PVRINOX","PVR Inox Ltd"],
["JUBLFOOD","Jubilant Foodworks Ltd"],["INDIGO","InterGlobe Aviation Ltd (IndiGo)"],["IRFC","Indian Railway Finance Corp"],
["RVNL","Rail Vikas Nigam Ltd"],["IRCON","Ircon International Ltd"],["BHEL","Bharat Heavy Electricals Ltd"],
["SAIL","Steel Authority Of India Ltd"],["NMDC","NMDC Ltd"],["NATIONALUM","National Aluminium Company Ltd"],
["JINDALSTEL","Jindal Steel & Power Ltd"],["APLAPOLLO","APL Apollo Tubes Ltd"],["ASTRAL","Astral Ltd"],
["SUPREMEIND","Supreme Industries Ltd"],["POLYCAB","Polycab India Ltd"],["HAVELLS","Havells India Ltd"],
["VOLTAS","Voltas Ltd"],["BLUESTARCO","Blue Star Ltd"],["CROMPTON","Crompton Greaves Consumer Electricals Ltd"],
["DIXON","Dixon Technologies India Ltd"],["AMBER","Amber Enterprises India Ltd"],["KAYNES","Kaynes Technology India Ltd"],
["PERSISTENT","Persistent Systems Ltd"],["COFORGE","Coforge Ltd"],["MPHASIS","Mphasis Ltd"],["LTTS","L&T Technology Services Ltd"],
["KPITTECH","KPIT Technologies Ltd"],["TATAELXSI","Tata Elxsi Ltd"],["ZYDUSLIFE","Zydus Lifesciences Ltd"],
["LUPIN","Lupin Ltd"],["AUROPHARMA","Aurobindo Pharma Ltd"],["ALKEM","Alkem Laboratories Ltd"],["TORNTPHARM","Torrent Pharmaceuticals Ltd"],
["BIOCON","Biocon Ltd"],["ABCAPITAL","Aditya Birla Capital Ltd"],["ABFRL","Aditya Birla Fashion & Retail Ltd"],
["PIIND","PI Industries Ltd"],["SRF","SRF Ltd"],["DEEPAKNTR","Deepak Nitrite Ltd"],["NAVINFLUOR","Navin Fluorine International Ltd"],
["TATAPOWER","Tata Power Company Ltd"],["ADANIGREEN","Adani Green Energy Ltd"],["ADANIENSOL","Adani Energy Solutions Ltd"],
["TATACOMM","Tata Communications Ltd"],["MOTHERSON","Samvardhana Motherson International Ltd"],["BOSCHLTD","Bosch Ltd"],
["ASHOKLEY","Ashok Leyland Ltd"],["TIINDIA","Tube Investments Of India Ltd"],["BALKRISIND","Balkrishna Industries Ltd"],
["MRF","MRF Ltd"],["CUMMINSIND","Cummins India Ltd"],["SIEMENS","Siemens Ltd"],["THERMAX","Thermax Ltd"],
["CONCOR","Container Corporation Of India Ltd"],["GMRAIRPORT","GMR Airports Ltd"],["INDHOTEL","Indian Hotels Company Ltd"],
["LODHA","Macrotech Developers Ltd (Lodha)"],["PHOENIXLTD","Phoenix Mills Ltd"],["ANGELONE","Angel One Ltd"],
["CDSL","Central Depository Services India Ltd"],["BSE","BSE Ltd"],["MCX","Multi Commodity Exchange Of India Ltd"],
["IEX","Indian Energy Exchange Ltd"],["CAMS","Computer Age Management Services Ltd"],["KFINTECH","KFin Technologies Ltd"]
];
